name: "MP0"
timeout: PT5M
version: 1.0.0
ignoreOutput:
  - "^java.security.policy: error parsing file.*"
  - "^Unable to initialize policy entry:.*"
  - "^.*?expected \\[\\;\\], found \\[priority\\]$"
vcs:
  git: true
students:
  location: email.txt
  require: true
  suffix: "@illinois.edu"
files:
  - "LCM"
  - "MaximumOfLastN"
  - "Quizzer"
secure: config/security.policy
reporting:
  post: "https://cs125-reporting.cs.illinois.edu/progress"
checkstyle:
  name: "checkstyle Tests"
  missing:
    score: 0
    message: "checkstyle failed to run"
    name: "checkstyle"
  selectors:
    - selector: "count(//file/error) = 0"
      score: 10
      message: "No checkstyle errors were reported"
      name: "checkstyle"
    - selector: "count(//file/error) > 0"
      score: 0
      message: "checkstyle errors were reported"
      name: "checkstyle"
test:
  name: "testNG Tests"
  selectors:
    - selector: "count(//testsuite[@name='LCMTest']) = 1 and count(//testsuite[@name='LCMTest']//failure) = 0"
      score: 30
      message: "No test failures in LCMTest"
      name: "LCMTest"
    - selector: "count(//testsuite[@name='LCMTest']) = 1 and count(//testsuite[@name='LCMTest']//failure) > 0"
      score: 10
      message: "Test failures in LCMTest"
      name: "LCMTest"
    - selector: "count(//testsuite[@name='LCMTest']) = 0"
      score: 0
      message: "LCMTest didn't compile"
      name: "LCMTest"
    - selector: "count(//testsuite[@name='MaximumOfLastNTest']) = 1 and count(//testsuite[@name='MaximumOfLastNTest']//failure) = 0"
      score: 30
      message: "No test failures in MaximumOfLastNTest"
      name: "MaximumOfLastNTest"
    - selector: "count(//testsuite[@name='MaximumOfLastNTest']) = 1 and count(//testsuite[@name='MaximumOfLastNTest']//failure) > 0"
      score: 10
      message: "Test failures in MaximumOfLastNTest"
      name: "MaximumOfLastNTest"
    - selector: "count(//testsuite[@name='MaximumOfLastNTest']) = 0"
      score: 0
      message: "MaximumOfLastNTest didn't compile"
      name: "MaximumOfLastNTest"
    - selector: "count(//testsuite[@name='QuizzerTest']) = 1 and count(//testsuite[@name='QuizzerTest']//failure) = 0"
      score: 30
      message: "No test failures in QuizzerTest"
      name: "QuizzerTest"
    - selector: "count(//testsuite[@name='QuizzerTest']) = 1 and count(//testsuite[@name='QuizzerTest']//failure) > 0"
      score: 10
      message: "Test failures in QuizzerTest"
      name: "QuizzerTest"
    - selector: "count(//testsuite[@name='QuizzerTest']) = 0"
      score: 0
      message: "QuizzerTest didn't compile"
      name: "QuizzerTest"

# vim: ts=2:sw=2:et
